### ISSUE TITLE
How to get just embed url?

### ISSUE THREAD

**Issue by devRMA** [KaneCohen/oembed#1]
How would I get just the url of the embed? With the ``url()`` method the original URL of the video is returned, but I would like to have the URL embed.

**Comment by KaneCohen** [comment]
There's not really an option for that. Library primarily works using OEmbed protocol which doesn't have a property for the URL of the actual embedded element.

You could try using `$embed->htmlBuilder()->toArray()` where `$embed` is an object that you get after providing url.
Code above will return associative array like so:

```php
[
  'type' => 'iframe' // or 'video' or 'raw'
  'html' => [
   'width' => 560,
    'height' => 315,
    'src' => 'https://www.youtube.com/embed/XYZ&feature=oembed',
    'frameborder' => '0',
    'allow' => 'accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture'
    'allowfullscreen' => '',
  ]
]
```

And from this you can extract `src` - but keep in mind that depending on the `type` of the embed resulting `html` contents might differ.

**Comment by devRMA** [comment]
> There's not really an option for that. Library primarily works using OEmbed protocol which doesn't have a property for the URL of the actual embedded element.
> 
> You could try using `$embed->htmlBuilder()->toArray()` where `$embed` is an object that you get after providing url.
> Code above will return associative array like so:
> 
> ```
> [
>   'type' => 'iframe' // or 'video' or 'raw'
>   'html' => [
>    'width' => 560,
>     'height' => 315,
>     'src' => 'https://www.youtube.com/embed/XYZ&feature=oembed',
>     'frameborder' => '0',
>     'allow' => 'accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture'
>     'allowfullscreen' => '',
>   ]
> ]
> ```
> 
> And from this you can extract `src` - but keep in mind that depending on the `type` of the embed resulting `html` contents might differ.

Thanks! I managed to do what I wanted!
