### ISSUE TITLE
Facebook oembed endpoint is deprecated/404, move to regex?

### ISSUE THREAD

**Issue by ChrisHardie** [KaneCohen/oembed#3]
It looks like the config for Facebook oembed endpoints may be out of date. For example, FB video URLs are queried at https://www.facebook.com/plugins/video/oembed.json but according to https://developers.facebook.com/docs/plugins/oembed-legacy/ that endpoint is no longer active or working. 

> The endpoints documented on this page were deprecated on October 24, 2020 and now return an error code 400. Please use the new Facebook oEmbed endpoints instead.

All of Facebook's documentation about their recommended new oEmbed handling, "[oEmbed Read](https://developers.facebook.com/docs/features-reference/oembed-read)," suggest the need for a reviewed/approved app to do basic embedding. Ugh. But within the Facebook UI I was able to retrieve their standard embed code for a public video, which does not seem to be authenticated or linked to an API key or app key in any way:

```
<iframe src="https://www.facebook.com/plugins/video.php?height=314&href=https%3A%2F%2Fwww.facebook.com%2Fusername%2Fvideos%12345%2F&show_text=false&width=560&t=0" width="560" height="314" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share" allowFullScreen="true"></iframe>
```

So, maybe some or all of Facebook's endpoints need to be moved over to regex versions in the config? FWIW I tried this in `regexProviders` and while it worked partially, some sandbox/content policy issues prevented the embedded video from playing:

```
        'facebook_video' => [
            'ssl' => true,
            'urls' => [
                '~^(https?://www\\.facebook\\.com/.*/videos/.*)$~imu',
            ],
            'data' => [
                'type' => 'video',
                'provider_name' => 'Facebook',
                'provider_url' => 'https://www.facebook.com',
                'width' => 560,
                'height' => 314,
                'html' => [
                    'iframe' => [
                        'src' => '{protocol}://www.facebook.com/plugins/video.php?href={1}&show_text=false&t=0&height=314&width=560',
                        'width' => 560,
                        'height' => 314,
                        'class' => 'embed-responsive-item',
                    ],
                ]
            ],
        ],
```

I'll keep playing with it but wanted to check in to see if a broader refactor is needed here.

**Comment by KaneCohen** [comment]
Hi, thanks for the report. I've noticed that few providers moved to auth-protected oembed API endpoints. For now I'll probably add regex would be a good choice. But I suppose it would be good to add an option to set API credentials for various providers so that full oembed options will be available.

**Comment by KaneCohen** [comment]
Closing this issue - I gave up on dealing with FB API authentication for this.
