### ISSUE TITLE
Getting a syntaz error syntax error, unexpected '|', expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by salamfall** [KaneCohen/oembed#4]
Using In (laravel 8 and php 7.4) blade i am using this code
<?php 
$embed = OEmbed::get("https://youtu.be/uifYHNyH-jA");
?>

and that's how I'm getting the error.

ParseError
syntax error, unexpected '|', expecting variable (T_VARIABLE) (View:

It's being throw in the OEmbedExtrator.php constructor on line 13 ( vendor/cohensive/oembed/src/OEmbedExtractor.php:13)
-> public function __construct(string|array $provider, string $url)
How come? and how to get it fixed

**Comment by KaneCohen** [comment]
This library is written for PHP 8 and above.

I can refer you to my previous library which has similar functionality but works on PHP 7: https://github.com/KaneCohen/embed

**Comment by salamfall** [comment]
Thanks a lot, maybe I should upgrade to php 8 and get it over with
