### ISSUE TITLE
Switch to underscore config naming breaks existing installations

### ISSUE THREAD

**Issue by ChrisHardie** [KaneCohen/oembed#5]
After much sleuthing today I figured out that https://github.com/KaneCohen/oembed/commit/9e49f3ec5f493d18a4aa5fc38f953c95054506da broke my existing installation because my already published config file was using the old `regexProviders` instead of the new `regex_providers` format.

Might it be worth a documentation note or changelog entry somewhere about this? In the future you might consider versioning the package and releases in a way that prevents someone from accidentally upgrading when there are breaking changes.

Thank you for all of your work on this great library!

**Comment by KaneCohen** [comment]
Right, apologies - I did a lot of config tweaks in that commit and it completely skipped my mind to note the config format change. I had the same problem on my installation until I realized the change from camelCase to snake_case format.

**Comment by KaneCohen** [comment]
Updated Readme and added CHANGELOG.md for future uses.
