### ISSUE TITLE
not detecting twitch embed

### ISSUE THREAD

**Issue by Azoruk** [KaneCohen/oembed#6]
It seems this no longer even detects twitch for embedding content. 

```
        $embed = Embed::make($url)->parseUrl();

        if ($embed) {
			dd('a');
            $submission->embedded_URL = $embed->getHtml();
        } else {
			dd('b');
            $submission->embedded_URL = null;
        }

```

I was trying to figure out why youtube clips were getting embedded, but not twitch. In the code example above, it seems that twitch clips are not being detected at all. I used https://clips.twitch.tv/NastyNaiveOysterOSsloth-pvt3cTngOPKyXWuf for my testing.

**Comment by Azoruk** [comment]
will this be fixed?

**Comment by KaneCohen** [comment]
Hi, this issue seems to be added for the wrong repo. This is OEmbed repo - while your code looks like you're using my older "Embed" repo:

https://github.com/KaneCohen/embed

I'll take a look what's causing the problem.

**Comment by KaneCohen** [comment]
For now, you can replace in your config.php file section for `twitchClip` with updated one:

        'twitchClip' => [
            'name' => 'Twitch',
            'type' => 'video',
            'website' => 'https://clips.twitch.tv',
            'ssl' => true,
            'url' => [
                '^(https?://)?clips.twitch\.tv/([a-zA-Z-_]+)$',
                '^(https?://)?(?:www\.)?twitch\.tv/(?:[0-9a-zA-Z-_]+)/clip/([0-9a-zA-Z-_]+)',
            ],
            'info' => [
                'id' => '{1}',
                'url' => '{protocol}://clips.twitch.tv/{1}',
            ],
            'render' => [
                'sizeRatio' => 1.70,
                'iframe' => [
                    'src' => '{protocol}://clips.twitch.tv/embed?clip={1}&autoplay=false&tt_medium=clips_embed&parent=www.example.com',
                    'width' => 420,
                    'height' => 237,
                    'scrolling' => 'no',
                    'allowfullscreen' => true,
                    'frameborder' => 0,
                    'sandbox' => 'allow-scripts allow-popups allow-same-origin allow-presentation',
                    'layout' => 'responsive',
                ],
            ],
            'data' => null,
            'dataCallback' => null,
        ],
        
        
Make sure to also change "parent=www.example.com" in the config to your own website. Otherwise video won't play.

**Comment by Azoruk** [comment]
Even when the  changing my \vendor\cohensive\embed\src\config\config.php 'twitchClip'  section to what you posted (with my parent URL), it returns false when using a twitch clip for $embed = Embed::make($url)->parseUrl();. But youtube works fine. 

Important to note that it returns false, not null.

**Comment by KaneCohen** [comment]
@Azoruk do you have a file config/ember,php in your configs folder (not the one in the library itself)? If you have it - then it is taking priority over the config file in `vendor/` folder. Update that file - generally you should never modify files in your `vendor/` folder.

**Comment by Azoruk** [comment]
I have both and they are the same. I edited both to have the same URL at the end of &parent=www.example.com',
oddly enough all other twitch sources work, just not twitch clips.

**Comment by KaneCohen** [comment]
@Azoruk hey, try this version of the same config:

```
    'twitchClip' => [
        'name' => 'Twitch',
        'type' => 'video',
        'website' => 'https://clips.twitch.tv',
        'ssl' => true,
        'url' => [
            '^(https?://)?clips\.twitch\.tv/([0-9a-zA-Z-_]+)$',
            '^(https?://)?(?:www\.)?twitch\.tv/(?:[0-9a-zA-Z-_]+)/clip/([0-9a-zA-Z-_]+)',
        ],
        'info' => [
            'id' => '{1}',
            'url' => '{protocol}://clips.twitch.tv/{1}',
        ],
        'render' => [
            'sizeRatio' => 1.70,
            'iframe' => [
                'src' => '{protocol}://clips.twitch.tv/embed?clip={1}&autoplay=false&tt_medium=clips_embed&parent=www.example.com',
                'width' => 420,
                'height' => 237,
                'scrolling' => 'no',
                'allowfullscreen' => true,
                'frameborder' => 0,
                'sandbox' => 'allow-scripts allow-popups allow-same-origin allow-presentation',
                'layout' => 'responsive',
            ],
        ],
        'data' => null,
        'dataCallback' => null,
    ],
```

**Comment by Azoruk** [comment]
@KaneCohen it works!
