### ISSUE TITLE
Not detecting Odysee embed

### ISSUE THREAD

**Issue by NecroSocial** [KaneCohen/oembed#9]
Odysee.com embeds aren't being recognized. This isn't my own site (trying to make the fix easy for the site owner to implement) so I don't have access to the source code however I do know the site uses the Laravel version of Oembed. Example of the script not recognizing Odysee embeds here: https://mainchan.com/s/featurerequest/3006/Video-embedding-for-Odysee and the code for Odysee embeds here: https://help.odysee.tv/contribute/#embedding

**Comment by KaneCohen** [comment]
@NecroSocial Hi,

Just tested - seems to be working fine. Please check if you have up to date version of oembed.php config file. And specifically look for odysee provider in there. If it's not present you might want to update your config file.

Latest config file can be seen here: https://github.com/KaneCohen/oembed/blob/master/resources/config.php

**Comment by NecroSocial** [comment]
Thanks for the reply, I've passed it on to the site admin. I'll give a heads up if this fixes the issue after he's updated the config.
